oas-tools/oas-tools

package-lock.json, package.json, src/index.js
=> Fixed bug with base path

package-lock.json, package.json, src/index.js, tests/testServer/index.js
#27 Primitive JSON request bodies threw an error
=> Fixed primitive JSON

.publishrc
The module publish-please checks for sensitive data but it does not seem to work correctly.
=> Added publish-please configuration

src/middleware/oas-router.js
[object Object] -> { <actual object content> }
=> make object vars readable in logger.debug

package-lock.json, package.json, schemas/validation-errors.json
=> Made variables readable on console

README.md, package-lock.json, package.json, src/configurations/configs.yaml, src/index.js, src/middleware/oas-auth.js, swagger-ui/index.html, tests/basic.js, tests/testServer/api/oai-spec.yaml, tests/testServer/configurations/customConfig.yaml, tests/testServer/controllers/petsController.js, tests/testServer/index.js
Improved coverage
#56 Added more settings to Swagger UI
Added checkControllers option
=> Added new features

.travis.yml, package-lock.json, package.json
The version number has been updated.
=> Updated version

.npmignore
base `.npmignore`. To address issue #99
=> base npmignore

src/middleware/oas-router.js
The swagger spec (https://swagger.io/docs/specification/describing-responses/) supports "range response codes".  This small fix adds support for those.
=> Add support for range responses (e.g: 2XX, 3XX, 4XX, 5XX)

src/index.js, src/middleware/oas-router.js, src/middleware/oas-validator.js
If x-swagger-router-controller appears in path but not in method, copy it to each method for that path.
=> Proposed Fix for Error when replacing swagger-tools with oas-tools #106

src/middleware/oas-security.js
FIX https://github.com/isa-group/oas-tools/issues/141
=> Report missing security scheme

src/lib/utils.js, src/middleware/oas-router.js, src/middleware/oas-validator.js
=> Don't mutate specDoc when validating

src/middleware/oas-security.js
fixes the problem that we don't get the array of roles in the security string array
=> fixes #146

src/middleware/oas-router.js, src/middleware/oas-validator.js
This is about issue #155 where my log4js logger complains.
=> customLogger support: replaced warning() by warn()

package-lock.json, package.json
All Travis CI builds were failing to due to a previous snyk updade made by Greenkeeper.
Moreover, vulnerabilities found with `npm audit` have also been fixed.
=> Fixed vulnerabilities and Travis build

src/middleware/oas-validator.js, tests/basic.js, tests/testServer/api/oai-spec.yaml, tests/testServer/controllers/Default.js, tests/testServer/controllers/petsController.js
Fixes https://github.com/isa-group/oas-tools/issues/168.
There was no request body validation if it was not required. I updated the validation logic and wrote some tests as well.
=> Add validation to optional request body

src/middleware/oas-auth.js, tests/basic.js, tests/testServer/api/oai-spec.yaml, tests/testServer/controllers/petsController.js
PR for https://github.com/isa-group/oas-tools/issues/172.
I included the two new methods in OAS-Auth with the corresponding permission requirements.
=> Add support for head and patch methods

src/index.js
Too many usefull info is masked for critical errors .
=> More verbose fatal errors 

README.md
In the source code there is no logLevel or logFile, but  loglevel and logfile
=> Wrong description

src/middleware/oas-validator.js, tests/basic.js, tests/testServer/api/oai-spec.yaml, tests/testServer/controllers/petsController.js
Fix for Issue #206
Make sure that we don't parse strings into integers by mistake.
=> Fix for incorrectly converting strings to integers

src/middleware/oas-router.js
Fixes: https://github.com/isa-group/oas-tools/issues/241
=> fix: fixNullable mutates oasDoc in oas-router

package-lock.json, package.json
Multer has been moved to dev-dependencies, since it is only used in tests.
=> v2.2.2 - Fixed critical vulnerability introduced by multer

src/middleware/oas-validator.js, tests/basic.mjs
Fixes https://github.com/oas-tools/oas-tools/issues/330
=> fix: query param failing if they are not string

package-lock.json, src/index_old.js
- Updated dependencies to solve minimatch vulnerability
- Fixed a bug caused by files starting with `.` when using backwards compatibility functions
=> Release v3.0.3
